### ISSUE TITLE
Questions about running the program

### ISSUE THREAD

**Issue by yuxiwang66** [yg13/Differential_Geometry_in_Edge_Detection#1]
![image](https://user-images.githubusercontent.com/29266819/46902473-a3cafa80-cef8-11e8-9cd2-b85749d030cb.png)

![image](https://user-images.githubusercontent.com/29266819/46902549-f0fb9c00-cef9-11e8-838e-64fc445a9df5.png)

I am interested in your project. so i want to run program in my computer.But i failed in this step"mex form_curvelet_mex.cxx CC_curve_model_3d.cxx curvelet.cxx curveletmap.cxx form_curvelet_process.cxx".The error message in the above image.To be honest. I have tryed to find many ways to solve this problem. But it doesn't work. I wish to get your help. 
(the version of my matlab is matlab 2017b.)

**Comment by yuliangguo** [comment]
Hi Yuxi, 

Thank for your interest and letting me know the error. Because this code was tested both on mac and linux, we did not see the errors before. It mostly about the library standards the VS has.

The following link explains how to solve the M_PI problem. 
http://www.cplusplus.com/forum/beginner/105176/
In short, M_PI is not defined in VS by default. For simplicity I have manually defined M_PI.

While for the conversion errors, there seems to be cross-platform datatype conversion issues involved. I convert 'int' to 'mwSize' for 'ds1' and 'ds2' to solve it.

Please pull my updated code, hope it solve your problem.

Best,

Yuliang

**Comment by yg13** [comment]
Hi Yuxi,

I have followed this link to solve the conversion problem, there seems to be cross-platform datatype conversion issues involved. I convert 'int' to 'mwSize' for 'ds1' and 'ds2' to solve the problem raised. 

Please pull again for my updated code, hope it solve your problem.

Best,

Yuliang
